### ISSUE TITLE
MySQL syntax highlight breaks within parentheses ()

### ISSUE THREAD

**Issue by m4ttclendenen** [atom/language-php#331]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The MySQL syntax highlighting breaks for SQL strings within the (), for example an "INSERT INTO" statement. Please see the attached images in Steps To Reproduce section ....

### Steps to Reproduce

1. This will occur within any set of () within a MySQL PHP string. Please see attached images for a better understanding.

**Expected behavior:**

If you remove the first parentheses, all is well ... except it would not be valid MySQL ...

![atomsyntax3](https://user-images.githubusercontent.com/9023946/40449645-16af0aa4-5ea7-11e8-9a26-8d59ec2bed64.png)

**Actual behavior:**

![atomsyntax](https://user-images.githubusercontent.com/9023946/40449449-76291c14-5ea6-11e8-8fad-23a4f7995390.png)

**Reproduces how often:** 

This happens wherever you include () ...

### Versions

atom 1.27.1
apm 1.19.0

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

**Comment by 50Wliu** [comment]
This was fixed by #330 and will be available in a future Atom version.

**Comment by Ingramz** [comment]
@50Wliu looks like it's not fixed, arguably changes from #330 made it worse.

![image](https://user-images.githubusercontent.com/1017132/40539349-271e0ad0-601d-11e8-8f27-dfae79a69950.png)

**Comment by m4ttclendenen** [comment]
Other than building from source, is there a way to get these latest changes into my language-php grammar?

**Comment by 50Wliu** [comment]
I have a fix.  Just needs some specs.
