### ISSUE TITLE
sql statement breaks syntax highlighting

### ISSUE THREAD

**Issue by nosilver4u** [atom/language-php#333]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

There seems to be an issue parsing a line of SQL code that results in the rest of the file being treated as a "string".

### Steps to Reproduce

1. Open this file in atom: https://github.com/nosilver4u/ewww-image-optimizer/blob/4944e9677f2d529e429ca6d87ebcd1664997e32c/common.php#L5193
2. scroll to line 5193
3. note the syntax highlighting goes wonky about halfway through that line.

### Versions

I'm running 1.27.2 on MacOS. The issue also occurred before I updated yesterday, and I believe I was running 1.25. On my linux desktop, running 1.23, the issue does not happen.

**Comment by nosilver4u** [comment]
found another example here:
https://github.com/nosilver4u/ewww-image-optimizer/blob/master/bulk.php#L1122

seems like the commonality here is the quoted part ends with a (

**Comment by Arcanemagus** [comment]
Thanks for reporting this!

This has already been fixed in https://github.com/atom/language-php/pull/330. It will be available in the next release of this package which should then begin to be integrated into Atom.

**Comment by nosilver4u** [comment]
Ah, very good, sorry for not catching that. I hadn't yet realized it was the parenthesis when I first filed the issue, and should have checked through the closed issues of course :)

**Comment by 50Wliu** [comment]
I'm going to reopen this because I may not have fixed this case.  Will check soon.

**Comment by nosilver4u** [comment]
I found several more examples last night when I was working on something else, so let me know if you need more samples for testing.

**Comment by 50Wliu** [comment]
Triaged.

**Comment by nyl2k8** [comment]
Here's another example of this issue. It appears to be occurring with only the first %. After the first, it escapes fine. 
<img width="616" alt="screen shot 2018-06-12 at 12 25 03" src="https://user-images.githubusercontent.com/5878890/41288346-e77b271c-6e3d-11e8-9b09-215c558204e7.png">

**Comment by 50Wliu** [comment]
@nyl2k8 I think your issue has been fixed and will be included in an upcoming Atom version.

This issue is specific to the string not ending if there are unbalanced parentheses.

**Comment by nyl2k8** [comment]
@50Wliu - I still have the same syntax issue after upgrading to v1.28.0 this morning. Must not be the same issue.

**Comment by stanfieldr** [comment]
pull request #332 seems to fix #331, but breaks the following case:

with #332 merged line 5 looks like a string, but $val2 is red:
![with_fix](https://user-images.githubusercontent.com/7494573/42128928-21a052a6-7c84-11e8-8963-8dbc861e4633.png)


with unmerged (number still green like a string, but variable was proper color):
![without_fix](https://user-images.githubusercontent.com/7494573/42128934-4e1442b6-7c84-11e8-87bd-53f14871faa6.png)

**Comment by jens1o** [comment]
Just don't allow SQL injection and you're done.

**Comment by louischan** [comment]
In v0.44.0, the issue can be reproduced by starting a string with one of these capitalised words `SELECT|INSERT|UPDATE|DELETE|CREATE|REPLACE|ALTER|AND`, followed by unbalanced parentheses.

For example,
```php
$string = 'AND (';
```
![example](https://user-images.githubusercontent.com/7802430/49995744-022f5a80-ffc8-11e8-9820-d1923d1ab86a.png)

**Comment by UziTech** [comment]
a minimal example

![image](https://user-images.githubusercontent.com/97994/50624517-c7de1c80-0ee6-11e9-9f0f-ba5fd05aef85.png)

**Comment by fdeblic** [comment]
Example in a real case, generating a where clause :
![screenshot](https://user-images.githubusercontent.com/17336611/50834592-b9fc2180-1354-11e9-9a18-9b89def011ad.png)

**Comment by nikolay1519** [comment]
Linux Mint 19.1
Atom 1.35.1
language-php 0.44.1

I think the sql syntax highlighting in php is not really needed. 100% everyone is used to seeing sql in php as simple strings, because in all editors and ide (notepad++, sublime, phpstorm, netbeans etc.) the sql queries in php are not highlighted as queries, but as simple strings.

If you don't want to remove the sql highlighting in php, then I suggest making a checkbox "Integrate sql" in settings. In this case, those who are vitally needed this highlighting will turn it on.

Thx

**Comment by Krinkle** [comment]
See also these reports, which are also about the handling of implicitly detected SQL-like syntax in string literals:

* https://github.com/atom/language-php/issues/327
* https://github.com/atom/language-php/issues/336
* https://github.com/atom/language-php/issues/361

Perhaps as a temporary solution this feature can be disabled for the time being?

The minimal value that color-coded words inside PHP strings adds to the developer experience, is presumably not worth it currently, given it almost always breaks the whole file as a result.

**Comment by gosukiwi** [comment]
This is still an issue 2 years later. Maybe removing the feature like @Krinkle suggested is the best option for now.

**Comment by samifouad** [comment]
I don't know how it's possible but switching to JavaScript highlighting for a PHP file seems to perform better than PHP highlighting on a PHP file. There is still breaks when SQL is embedded in a file. It's near the end of 2020 now. Is there any fix on the horizon? 

Or suggestions on some code we can hack to get around this annoying bug?

**Comment by samifouad** [comment]
I was just testing other languages and it looks like C++ highlighting on a PHP file does not have syntax highlighting break due to SQL.

So I guess this is a fix but this is kind of silly to be the solution.

**Comment by seth-xdam** [comment]
Why was this closed? This is still broken...

**Comment by KapitanOczywisty** [comment]
@seth-xdam This was closed from #359 , but imo PR was merged by mistake. I wouldn't count for definitive fix of SQL embedded syntax though, this needs changes to TM grammar engine, and no one wants to touch this. I'll ask directly atom team about this PR.

**Comment by seth-xdam** [comment]
@KapitanOczywisty Got it. SQL highlighting would be great, but I'd accept it being off instead of having it break the PHP highlighting.
